version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: dash-bot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: dashbot
      POSTGRES_USER: dashbot
      POSTGRES_PASSWORD: dashbot123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dashbot -d dashbot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
