# fly.toml app configuration file for dash-bot-telegram
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dash-bot-telegram'
primary_region = 'gig'

[build]

[env]
  NODE_ENV = "production"
  # Outras variáveis não-sensíveis podem ser definidas aqui
  # As sensíveis (tokens, URLs de banco) devem ser definidas como secrets

# Process configuration for the bot
[processes]
  app = "npm run start"

# Configuração de deploy
[deploy]
  strategy = "immediate"
  
# Configuração de máquinas
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Configuração de restart automático
[restart]
  policy = "on-failure"
  max_restarts = 5

# Health checks para monitorar o bot
[checks]
  [checks.bot_health]
    type = "script"
    command = "pgrep -f 'node.*bot.js' || pgrep -f 'npm.*start'"
    interval = "30s"
    timeout = "10s"
    grace_period = "30s"

# Configuração de logs
[metrics]
  port = 9091
  path = "/metrics"
